#pragma once
#include <sysio/vm/opcodes_def.hpp>
#include <sysio/vm/variant.hpp>

#include <map>

namespace sysio { namespace vm {
   enum opcodes {
      SYS_VM_CONTROL_FLOW_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_BR_TABLE_OP(SYS_VM_CREATE_ENUM)
      SYS_VM_RETURN_OP(SYS_VM_CREATE_ENUM)
      SYS_VM_CALL_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_CALL_IMM_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_PARAMETRIC_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_VARIABLE_ACCESS_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_MEMORY_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_I32_CONSTANT_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_I64_CONSTANT_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_F32_CONSTANT_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_F64_CONSTANT_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_COMPARISON_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_NUMERIC_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_CONVERSION_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_EXIT_OP(SYS_VM_CREATE_ENUM)
      SYS_VM_EMPTY_OPS(SYS_VM_CREATE_ENUM)
      SYS_VM_ERROR_OPS(SYS_VM_CREATE_ENUM)
   };

   struct opcode_utils {
      std::map<uint16_t, std::string> opcode_map{
         SYS_VM_CONTROL_FLOW_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_BR_TABLE_OP(SYS_VM_CREATE_MAP)
         SYS_VM_RETURN_OP(SYS_VM_CREATE_MAP)
         SYS_VM_CALL_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_CALL_IMM_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_PARAMETRIC_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_VARIABLE_ACCESS_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_MEMORY_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_I32_CONSTANT_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_I64_CONSTANT_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_F32_CONSTANT_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_F64_CONSTANT_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_COMPARISON_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_NUMERIC_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_CONVERSION_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_EXIT_OP(SYS_VM_CREATE_MAP)
         SYS_VM_EMPTY_OPS(SYS_VM_CREATE_MAP)
         SYS_VM_ERROR_OPS(SYS_VM_CREATE_MAP)
      };
   };

   enum imm_types {
      none,
      block_imm,
      varuint32_imm,
      br_table_imm,
   };


   SYS_VM_CONTROL_FLOW_OPS(SYS_VM_CREATE_CONTROL_FLOW_TYPES)
   SYS_VM_BR_TABLE_OP(SYS_VM_CREATE_BR_TABLE_TYPE)
   SYS_VM_RETURN_OP(SYS_VM_CREATE_CONTROL_FLOW_TYPES)
   SYS_VM_CALL_OPS(SYS_VM_CREATE_CALL_TYPES)
   SYS_VM_CALL_IMM_OPS(SYS_VM_CREATE_CALL_IMM_TYPES)
   SYS_VM_PARAMETRIC_OPS(SYS_VM_CREATE_TYPES)
   SYS_VM_VARIABLE_ACCESS_OPS(SYS_VM_CREATE_VARIABLE_ACCESS_TYPES)
   SYS_VM_MEMORY_OPS(SYS_VM_CREATE_MEMORY_TYPES)
   SYS_VM_I32_CONSTANT_OPS(SYS_VM_CREATE_I32_CONSTANT_TYPE)
   SYS_VM_I64_CONSTANT_OPS(SYS_VM_CREATE_I64_CONSTANT_TYPE)
   SYS_VM_F32_CONSTANT_OPS(SYS_VM_CREATE_F32_CONSTANT_TYPE)
   SYS_VM_F64_CONSTANT_OPS(SYS_VM_CREATE_F64_CONSTANT_TYPE)
   SYS_VM_COMPARISON_OPS(SYS_VM_CREATE_TYPES)
   SYS_VM_NUMERIC_OPS(SYS_VM_CREATE_TYPES)
   SYS_VM_CONVERSION_OPS(SYS_VM_CREATE_TYPES)
   SYS_VM_EXIT_OP(SYS_VM_CREATE_EXIT_TYPE)
   SYS_VM_EMPTY_OPS(SYS_VM_CREATE_TYPES)
   SYS_VM_ERROR_OPS(SYS_VM_CREATE_TYPES)

   using opcode = variant<
      SYS_VM_CONTROL_FLOW_OPS(SYS_VM_IDENTITY)
      SYS_VM_BR_TABLE_OP(SYS_VM_IDENTITY)
      SYS_VM_RETURN_OP(SYS_VM_IDENTITY)
      SYS_VM_CALL_OPS(SYS_VM_IDENTITY)
      SYS_VM_CALL_IMM_OPS(SYS_VM_IDENTITY)
      SYS_VM_PARAMETRIC_OPS(SYS_VM_IDENTITY)
      SYS_VM_VARIABLE_ACCESS_OPS(SYS_VM_IDENTITY)
      SYS_VM_MEMORY_OPS(SYS_VM_IDENTITY)
      SYS_VM_I32_CONSTANT_OPS(SYS_VM_IDENTITY)
      SYS_VM_I64_CONSTANT_OPS(SYS_VM_IDENTITY)
      SYS_VM_F32_CONSTANT_OPS(SYS_VM_IDENTITY)
      SYS_VM_F64_CONSTANT_OPS(SYS_VM_IDENTITY)
      SYS_VM_COMPARISON_OPS(SYS_VM_IDENTITY)
      SYS_VM_NUMERIC_OPS(SYS_VM_IDENTITY)
      SYS_VM_CONVERSION_OPS(SYS_VM_IDENTITY)
      SYS_VM_EXIT_OP(SYS_VM_IDENTITY)
      SYS_VM_EMPTY_OPS(SYS_VM_IDENTITY)
      SYS_VM_ERROR_OPS(SYS_VM_IDENTITY_END)
      >;
}} // namespace sysio::vm
